module.exports = {
  operation: {
    perform: {
      url:
        'https://{{bundle.authData.domain}}/api/v2/users/{{bundle.inputData.user_id}}',
      method: 'PATCH',
      params: {
        client_id: '{{bundle.authData.client_id}}',
        client_secret: '{{bundle.authData.client_secret}}',
        domain: '{{bundle.authData.domain}}',
      },
      headers: {
        'Content-Type': 'application/json',
        authorization: 'Bearer {{bundle.authData.access_token}}',
      },
      body: {
        blocked: '{{bundle.inputData.blocked}}',
        email: '{{bundle.inputData.email}}',
        email_verified: '{{bundle.inputData.email_verified}}',
        family_name: '{{bundle.inputData.family_name}}',
        given_name: '{{bundle.inputData.given_name}}',
        name: '{{bundle.inputData.name}}',
        nickname: '{{bundle.inputData.nickname}}',
        password: '{{bundle.inputData.password}}',
        phone_number: '{{bundle.inputData.phone_number}}',
        phone_verified: '{{bundle.inputData.phone_verified}}',
        picture: '{{bundle.inputData.picture}}',
        username: '{{bundle.inputData.username}}',
        connection: '{{bundle.inputData.connection}}',
        client_id: '{{bundle.inputData.client_id}}',
      },
      removeMissingValuesFrom: { params: true, body: true },
    },
    inputFields: [
      {
        key: 'user_id',
        label: 'User ID',
        type: 'string',
        helpText: 'auth0|xxxxxxxxxxxxxxxxxxxx',
        required: true,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'blocked',
        label: 'Blocked',
        type: 'boolean',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'email',
        label: 'Email',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'email_verified',
        label: 'Email Verified',
        type: 'boolean',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'family_name',
        label: 'Family Name',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'given_name',
        label: 'Given Name',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'name',
        label: 'Name',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'nickname',
        label: 'Nickname',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'password',
        label: 'Password',
        type: 'string',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'phone_number',
        label: 'Phone Number',
        type: 'string',
        helpText:
          "The user's phone number (following the E.164 recommendation), only valid for users from SMS connections.",
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'phone_verified',
        label: 'Phone Verified',
        type: 'boolean',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'picture',
        label: 'Picture',
        type: 'string',
        helpText: 'URL to picture, photo, or avatar of this user.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'username',
        label: 'Username',
        type: 'string',
        helpText:
          "The user's username. Only valid if the connection requires a username.",
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'connection',
        label: 'Connection',
        type: 'string',
        helpText: 'ID of the connection this user should be created in.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
      {
        key: 'client_id',
        label: 'Client ID',
        type: 'string',
        helpText: 'Auth0 client ID. Only valid when updating email address.',
        required: false,
        list: false,
        altersDynamicFields: false,
      },
    ],
  },
  key: 'update_user',
  noun: 'User',
  display: {
    label: 'Update User',
    description:
      'Update an Existing User\n\nIf you are updating email, email_verified, phone_number, phone_verified, username or password of a secondary identity, you need to specify the connection property too.',
    hidden: false,
    important: true,
  },
};
